const sampleListings = [
    {
      title: "Fresh Organic Apples",
      description: "https://media.istockphoto.com/id/614871876/photo/apple-isolated-on-wood-background.jpg?s=1024x1024&w=is&k=20&c=HlmdzA8HWMiVdSicwDiEa77FSxQEEvxm6nGzeSRGBZ4=",
      price: 3,
      location: "Downtown",
      country: "United States",
      range: "500 meters",
      quantity: 20,
      sellerName: "Tom Green",
      distanceToBuyer: "300 meters",
    },
    {
      title: "Organic Free-Range Eggs (1 dozen)",
      description: "Fresh, free-range eggs from a local farm, packed with nutrients.",
      image: "https://plus.unsplash.com/premium_photo-1677247567623-78a3f4b26bb3?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: 5,
      location: "Neighborhood Market",
      country: "United States",
      range: "500 meters",
      quantity: 12,
      sellerName: "Lisa Brown",
      distanceToBuyer: "200 meters",
    },
    {
      title: "Home-Grown Spinach (500g)",
      description: "Fresh spinach harvested from a local garden, packed with nutrients.",
      image: "https://images.unsplash.com/photo-1519995672084-d21490e86ba6?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: 2,
      location: "Near Park",
      country: "United States",
      range: "500 meters",
      quantity: 15,
      sellerName: "Mike Johnson",
      distanceToBuyer: "150 meters",
    },
    {
      title: "Homemade Whole Grain Bread (1 loaf)",
      description: "Freshly baked whole grain bread, perfect for sandwiches or toast.",
      image: "https://plus.unsplash.com/premium_photo-1667806855292-111b1d9bec4c?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: 4,
      location: "Suburban Area",
      country: "United States",
      range: "500 meters",
      quantity: 10,
      sellerName: "Alice Baker",
      distanceToBuyer: "400 meters",
    },
    {
      title: "Locally Sourced Fresh Milk (1 liter)",
      description: "Rich and creamy milk from local dairy, delivered fresh.",
      image: "https://images.unsplash.com/photo-1574226516831-e1dff4208038?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
      price: 2,
      location: "Residential Block",
      country: "United States",
      range: "500 meters",
      quantity: 25,
      sellerName: "John Smith",
      distanceToBuyer: "100 meters",
    },
    {
      title: "Fresh Strawberries (500g)",
      description: "Sweet and juicy strawberries, perfect for desserts or smoothies.",
      image: "https://images.unsplash.com/photo-1591271300850-22d6784e0a7f?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: 4,
      location: "Market Street",
      country: "United States",
      range: "500 meters",
      quantity: 30,
      sellerName: "Emma White",
      distanceToBuyer: "250 meters",
    },
    {
      title: "Local Honey (500g)",
      description: "Pure honey sourced from local beekeepers, rich and flavorful.",
      image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: 8,
      location: "Greenfield",
      country: "United States",
      range: "500 meters",
      quantity: 10,
      sellerName: "Charlie Green",
      distanceToBuyer: "150 meters",
    },
    {
      title: "Fresh Tomatoes (1kg)",
      description: "Vibrant, juicy tomatoes for all your cooking needs.",
      image: "https://plus.unsplash.com/premium_photo-1664527305909-ddfb1ef9f5e8?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: 3,
      location: "Market Area",
      country: "United States",
      range: "500 meters",
      quantity: 25,
      sellerName: "Sophia James",
      distanceToBuyer: "500 meters",
    },
    {
      title: "Home-Made Jam (250g)",
      description: "Delicious homemade strawberry jam, made with love.",
      image: "https://plus.unsplash.com/premium_photo-1663850873018-b5e8b108d95c?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: 6,
      location: "Farmers Market",
      country: "United States",
      range: "500 meters",
      quantity: 15,
      sellerName: "Olivia Taylor",
      distanceToBuyer: "300 meters",
    },
    {
      title: "Fresh Carrots (1kg)",
      description: "Crunchy and sweet carrots, perfect for snacking or cooking.",
      image: "https://plus.unsplash.com/premium_photo-1664277022334-de9ab23c0ee2?q=80&w=2047&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: 2,
      location: "Main Street",
      country: "United States",
      range: "500 meters",
      quantity: 18,
      sellerName: "Liam Brown",
      distanceToBuyer: "180 meters",
    },
    {
      title: "Organic Potatoes (2kg)",
      description: "Earthy, organic potatoes perfect for any dish.",
      image: "https://plus.unsplash.com/premium_photo-1677528816982-673398569f03?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8T3JnYW5pYyUyMFBvdGF0b2VzJTIwKDJrZyl8ZW58MHx8MHx8fDA%3D",
      price: 3,
      location: "Green Market",
      country: "United States",
      range: "500 meters",
      quantity: 12,
      sellerName: "Isabella King",
      distanceToBuyer: "250 meters",
    },
    {
      title: "Fresh Lettuce (500g)",
      description: "Crisp, fresh lettuce, ideal for salads.",
      image: "https://images.unsplash.com/photo-1517260739337-6799d239ce83?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8RnJlc2glMjBMZXR0dWNlJTIwKDUwMGcpfGVufDB8fDB8fHww",
      price: 2,
      location: "Greenfield",
      country: "United States",
      range: "500 meters",
      quantity: 20,
      sellerName: "James Lee",
      distanceToBuyer: "100 meters",
    },
    
  ];
  
  module.exports = { data: sampleListings };